kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  host: {{ .Values.route.host }}
  port:
    targetPort: http
