apiVersion: v1
kind: Secret
metadata:
  name: mongodb-users-secret
  labels:
    {{- include "pacman-kubernetes.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque 
data:
  database-name: {{ ( printf .Values.mongo.databaseName | b64enc ) | default "cGFjbWFu" }}
  database-password: {{ ( printf .Values.mongo.databasePassword | b64enc ) | default "cGlua3k=" }}
  database-user: {{ ( printf .Values.mongo.databaseUser | b64enc ) | default "Ymxpbmt5" }}