apiVersion: v1
kind: Service
metadata:
  name: {{ include "pacman-kubernetes.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pacman-kubernetes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "pacman-kubernetes.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: db
  type: ClusterIP