apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k10-demo
spec:
  destination:
    namespace: k10-demo
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: ''
    targetRevision: HEAD
  sources:
    - name: values
      path: values
      repoURL: https://github.com/YotamKorah/k10-gitops-demo-charts.git
      targetRevision: main
      ref: values
    - name: kasten
      repoURL: https://github.com/YotamKorah/k10-gitops-demo-charts.git
      path: charts/k10-demo
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
          - $values/values/k10-demo-app.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
